@echo off
echo [*] Installing/Updating dependencies...
pip install -r requirements.txt --quiet
echo [*] Discovering new novels...
python discover_novels.py
echo [*] Checking for new chapters...
python check_updates.py
echo [*] Running Novel Sync...
python sync_novels.py
echo [*] Done.
pause
